extend = "Base.toml"
[tasks.build-release.mac]
args = [
    "build",
    "--release",
    "--target=x86_64-apple-darwin",
    "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"
]

[tasks.build-release.linux]
dependencies = ["setup-musl"]
args = [
    "build",
    "--release",
    "--target=x86_64-unknown-linux-musl",
    "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"
]

[tasks.setup-musl.linux]
script = '''
sudo apt-get update
sudo apt-get install -y musl-tools build-essential
rustup target add "$CARGO_MAKE_RELEASE_FLOW_TARGET"
'''

[tasks.setup-musl.condition]
platforms = ["linux"]
profiles = [ "production" ]


[tasks.setup-musl.env]
CARGO_MAKE_RELEASE_FLOW_TARGET = "x86_64-unknown-linux-musl"

[tasks.install-github-release.mac]
script = '''
github-release --help 2> /dev/null || {
    go get github.com/github-release/github-release;
    ls $(go env GOPATH)/bin;
    cp $(go env GOPATH)/bin/github-release /usr/local/bin;
}
'''

[tasks.install-github-release.linux]
script = '''
github-release --help 2> /dev/null || {
    go get github.com/github-release/github-release;
    export PATH=$PATH:$(go env GOPATH)/bin/;
}
'''


[tasks.github-release-upload]
description = "Upload release binaries to Github"
category = "Publish"
dependencies = [
    "release-github-env",
    "install-github-release",
    "build-release",
]
command = "github-release"
args = [
    "upload",
    "--user", "infinyon",
    "--repo", "fluvio",
    "--tag", "v${GIT_TAG}",
    "--name", "fluvio-v${GIT_TAG}-${TARGET}",
    "--file", "target/${TARGET}/release/fluvio",
]

[tasks.github-release-publish]
description = "Publish release binaries to Github"
category = "Publish"
dependencies = [
    "release-github-env",
    "install-github-release",
    "build-release",
]
command = "github-release"
args = [
    "publish",
    "--user", "infinyon",
    "--repo", "fluvio",
    "--tag", "v${GIT_TAG}",
    "--name","v${GIT_TAG}",
]

[tasks.release-github-env.linux]
env = { TARGET = "x86_64-unknown-linux-musl" }

[tasks.release-github-env.mac]
env = { TARGET = "x86_64-apple-darwin" }

[tasks.delete-github-release]
command = "github-release"
args = [
    "delete",
    "--user", "infinyon",
    "--repo", "fluvio",
    "--tag", "v${GIT_TAG}",
]
